## 使用Jedis连接池配置
spring:
  redis:
    timeout: 6000
    password:
    cluster:
      nodes: 10.4.3.109:6379,10.4.3.109:6380
    jedis:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1